### ISSUE TITLE
64bit wrapper

### ISSUE THREAD

**Issue by rollsch** [MEAT-Inc/SharpWrap2534#77]
I would love to be able to write a 64bit C# application that can call 32bit J2534 DLLs (or any x86 32 bit DLL for that matter). It would require a separate process and to communicate via shared memory, windows pipes or something along those lines.

Have you ever considered doing something like this?

**Comment by ZacharyWalsh57** [comment]
Hey I never saw this issue get opened up somehow. It is in fact something I considered doing for sure but never got around to it. 

Now the question is why do you wanna be able to do this?

**Comment by rollsch** [comment]
I have an application which needs multiple gb of ram for datalogging and various other activities. Being limited to 32bit massively restrains how much memory I can use. 64bit program with a wrapper for a 32bit J2534 dll would be awesome.

**Comment by rollsch** [comment]
Using this library which is super memory hungry. Couple it with a bunch of other scatter plots and 1000s of channels and you can use up 2gb of memory after an hour or so. It is more the high memory pressure that is the issue of your have say 5 datalogs open and are doing a high speed log at the same time. 

https://lightningchart.com/

**Comment by ZacharyWalsh57** [comment]
Yeah I See that now lol.
Lemme dig into this a little bit in my free time and see what I can do for you.

**Comment by rollsch** [comment]
That would be awesome. Let me know how you go and I can do some testing for you.

**Comment by testuser7** [comment]
There is an x64 driver implementation for Tactrix Openport 2.0: https://github.com/dschultzca/j2534/releases/tag/3.0.0

**Comment by rollsch** [comment]
Great find

**Comment by rollsch** [comment]
> There is an x64 driver implementation for Tactrix Openport 2.0: https://github.com/dschultzca/j2534/releases/tag/3.0.0

Just FYI this doesn't work on Windows without molesting your usb configuration to use libusb. Even then I could never get the driver to work.

Even if it did work the libusb config is not user friendly and would be beyond any typical user to do.
